version: "2"
services:
  manila-share:
    image: manila-1
    environment:
      MANILA_DBUSER: "manila"
      MANILA_DBPASS: "Welcome123"
      DB_IP_ADDR: "10.0.0.21"
      MANILA_DBNAME: "manila"
      CONTROLLER_ADDR: "10.0.0.21"
      RABBIT_USERID: "openstack"
      RABBIT_PASS: "Welcome123"
      PROJECT_DOMAIN_NAME: "default"
      USER_DOMAIN_NAME: "default"
      PROJECT_NAME: "service"
      USER_MANILA: "manila"
      MANILA_PASS: "Welcome123"
      BACKEND_NAME: "backend1"
      DRIVER: "ganesha"
      GANESHA_ADDR: "10.0.0.28"
      GANESHA_USER: "root"
      GANESHA_PASS: "saphi"
    entrypoint: ["/home/manila/entrypoint.sh"]
